name: logopedy
description: "Aplicatie logopedica"
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  equatable: ^2.0.5
  get_it: ^9.0.5
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.2
  connectivity_plus: ^7.0.0
  formz: ^0.8.0
  intl: ^0.20.2
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  audioplayers: ^6.5.1
  package_info_plus: ^9.0.0
  cached_network_image: ^3.3.1
  path_provider: ^2.1.4
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/app_icon/app_icon.png   # ideal 1024×1024
  remove_alpha_ios: true
  # (opțional pentru Android 8+)
  # adaptive_icon_foreground: assets/app_icon/fg.png
  # adaptive_icon_background: "#FFFFFF"

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_light.png
    - assets/images/logo_dark.png
    - assets/images/login_image.png
    - assets/images/signup_image.png
    - assets/images/forgot_password.png
    - assets/images/reset_password.png
    - assets/images/applause.gif
    - assets/images/finish_lesson.png
    - assets/images/finish_submodule copy.png
    - assets/images/finish_module.png
    - assets/images/
    - assets/audio/